LedController: sakurajin::ByteBlock Class Reference
sakurajin::ByteBlock Class Reference
A block of bytes used to represent all of the data in a Segment.
#include <LedController_byteblock.hpp>
Public Member Functions
ByteBlock () noexcept
Construct a new Byte Block object with 0s.
ByteBlock (byte n0, byte n1, byte n2, byte n3, byte n4, byte n5, byte n6, byte n7) noexcept
Construct a new Byte Block object from a list of values.
ByteBlock (byte newdata[8]) noexcept
Construct a new Byte Block object from an array.
ByteBlock (const ByteRow< 8 > &data) noexcept
Construct a new Byte Block object from a byteRow.
ByteBlock makeColumns () const noexcept
Turns an ByteBlock of rows into an ByteBlock of columns.
ByteBlock reverse () const noexcept
Reverse an ByteBlock of 8 bytes (mirror it)
ByteBlock rotate180 () const noexcept
rotate an ByteBlock by 180 degrees
ByteBlock transpose () const noexcept
Turns an ByteBlock of rows into an ByteBlock of columns.
Public Member Functions inherited from sakurajin::ByteRow< 8 >
byte at (uint64_t index) const noexcept
Access the class just like the underlying array.
ByteRow () noexcept
Construct a new Byte Row object with 0s.
ByteRow (byte newdata[SIZE]) noexcept
Construct a new Byte Row object from an array.
virtual bool operator!= (const ByteRow< SIZE > &other) const noexcept
checks if two byteRows do not have identical data
virtual ByteRow operator& (const ByteRow< SIZE > &other) const noexcept
Overlaps two ByteRows (bitwise or).
virtual ByteRow operator++ () const noexcept
Moves all data of the ByteRow to the up by one.
virtual ByteRow operator-- () const noexcept
Moves all data of the ByteRow to the down by one.
virtual ByteRow operator<< (unsigned int distance) const noexcept
Moves all data of the ByteRow to the left by a given distance.
ByteRow & operator= (byte newdata[SIZE]) noexcept
Assign an array to this object.
virtual bool operator== (const ByteRow< SIZE > &other) const noexcept
checks if two byteRows have identical data
virtual ByteRow operator>> (unsigned int distance) const noexcept
Moves all data of the ByteRow to the right by a given distance.
const byte & operator[] (uint64_t index) const noexcept
Access the class just like the underlying array.
byte & operator[] (uint64_t index) noexcept
Access the class just like the underlying array.
~ByteRow () noexcept
Destroy the Byte Row object.
Static Public Member Functions
static ByteBlock makeColumns (ByteBlock rowArray) noexcept
Turns an ByteBlock of rows into an ByteBlock of columns.
static byte reverse (byte input) noexcept
This function changes to bitorder of a byte (useful to mirror "images" you want to display)
static ByteBlock reverse (ByteBlock input) noexcept
Reverse an ByteBlock of 8 bytes (mirror it)
static ByteBlock rotate180 (ByteBlock input) noexcept
rotate an ByteBlock by 180 degrees
static ByteBlock transpose (ByteBlock rowArray) noexcept
Turns an ByteBlock of rows into an ByteBlock of columns.
Additional Inherited Members
Protected Attributes inherited from sakurajin::ByteRow< 8 >
byte _data [SIZE]
The internal array where the actual data is.
Detailed Description
A block of bytes used to represent all of the data in a Segment.
It is simply a ByteRow with size 8 but useful regardless.
Definition at line 26 of file LedController_byteblock.hpp.
Constructor & Destructor Documentation
ByteBlock() [1/4]
sakurajin::ByteBlock::ByteBlock (byte newdata[8]) inline noexcept
Construct a new Byte Block object from an array.
Parameters
newdata The array which should be used to initilize the row.
Definition at line 40 of file LedController_byteblock.hpp.
ByteBlock() [2/4]
sakurajin::ByteBlock::ByteBlock (byte n0, byte n1, byte n2, byte n3, byte n4, byte n5, byte n6, byte n7) inline noexcept
Construct a new Byte Block object from a list of values.
This way {0,0,0,0,0,0,0,0} can be used as copy-assignement.
Definition at line 51 of file LedController_byteblock.hpp.
References sakurajin::ByteRow< 8 >::_data.
ByteBlock() [3/4]
sakurajin::ByteBlock::ByteBlock () inline noexcept
Construct a new Byte Block object with 0s.
Definition at line 69 of file LedController_byteblock.hpp.
ByteBlock() [4/4]
sakurajin::ByteBlock::ByteBlock (const ByteRow< 8 > & data) inline noexcept
Construct a new Byte Block object from a byteRow.
Note
This constructor mainly exists for automatic casting.
Parameters
data the data that should be assigned
Definition at line 82 of file LedController_byteblock.hpp.
Member Function Documentation
makeColumns() [1/2]
ByteBlock sakurajin::ByteBlock::makeColumns () const inline noexcept
Turns an ByteBlock of rows into an ByteBlock of columns.
Returns
ByteBlock The Columns of the given ByteBlock
Definition at line 110 of file LedController_byteblock.hpp.
References transpose().
makeColumns() [2/2]
static ByteBlock sakurajin::ByteBlock::makeColumns (ByteBlock rowArray) inline static noexcept
Turns an ByteBlock of rows into an ByteBlock of columns.
Parameters
rowArray the ByteBlock of rows of which you want the columns of
Returns
ByteBlock The Columns of the given ByteBlock
Definition at line 227 of file LedController_byteblock.hpp.
References ByteBlock(), and reverse().
reverse() [1/3]
ByteBlock sakurajin::ByteBlock::reverse () const inline noexcept
Reverse an ByteBlock of 8 bytes (mirror it)
Returns
ByteBlock The reversed ByteBlock
Definition at line 125 of file LedController_byteblock.hpp.
reverse() [2/3]
static byte sakurajin::ByteBlock::reverse (byte input) inline static noexcept
This function changes to bitorder of a byte (useful to mirror "images" you want to display)
Parameters
input The byte that should be reversed
Returns
byte The reversed byte
Definition at line 158 of file LedController_byteblock.hpp.
reverse() [3/3]
static ByteBlock sakurajin::ByteBlock::reverse (ByteBlock input) inline static noexcept
Reverse an ByteBlock of 8 bytes (mirror it)
Parameters
input The ByteBlock that should be mirrored
Returns
ByteBlock The reversed ByteBlock
Definition at line 181 of file LedController_byteblock.hpp.
References ByteBlock(), and reverse().
rotate180() [1/2]
ByteBlock sakurajin::ByteBlock::rotate180 () const inline noexcept
rotate an ByteBlock by 180 degrees
Returns
ByteBlock The rotated ByteBlock
Definition at line 140 of file LedController_byteblock.hpp.
rotate180() [2/2]
static ByteBlock sakurajin::ByteBlock::rotate180 (ByteBlock input) inline static noexcept
rotate an ByteBlock by 180 degrees
Parameters
input the ByteBlock that will be rotated
Returns
ByteBlock The rotated ByteBlock
Definition at line 204 of file LedController_byteblock.hpp.
References ByteBlock(), and reverse().
transpose() [1/2]
ByteBlock sakurajin::ByteBlock::transpose () const inline noexcept
Turns an ByteBlock of rows into an ByteBlock of columns.
Returns
ByteBlock The Columns of the given ByteBlock
Definition at line 95 of file LedController_byteblock.hpp.
References makeColumns().
transpose() [2/2]
static ByteBlock sakurajin::ByteBlock::transpose (ByteBlock rowArray) inline static noexcept
Turns an ByteBlock of rows into an ByteBlock of columns.
Parameters
rowArray the ByteBlock of rows of which you want the columns of
Returns
ByteBlock The Columns of the given ByteBlock
Definition at line 252 of file LedController_byteblock.hpp.
References makeColumns().
The documentation for this class was generated from the following file:
src/LedController_byteblock.hpp