LedController: test/common/common.cpp File Reference
common.cpp File Reference
#include "common.hpp"
Functions
controller_configuration< 4, 1 > & get_conf ()
controller_configuration< 4, 1 > & get_conf_SPI ()
controller_configuration< 4, 4 > & get_multi_conf ()
controller_configuration< 4, 4 > & get_multi_conf_SPI ()
Function Documentation
get_conf()
controller_configuration<4,1>& get_conf ()
Definition at line 3 of file common.cpp.
References controller_configuration< columns, rows >::isValid(), controller_configuration< columns, rows >::SPI_CLK, controller_configuration< columns, rows >::SPI_CS, controller_configuration< columns, rows >::SPI_MOSI, and controller_configuration< columns, rows >::useHardwareSpi.
get_conf_SPI()
controller_configuration<4,1>& get_conf_SPI ()
Definition at line 16 of file common.cpp.
References controller_configuration< columns, rows >::isValid(), controller_configuration< columns, rows >::SPI_CS, and controller_configuration< columns, rows >::useHardwareSpi.
get_multi_conf()
controller_configuration<4,4>& get_multi_conf ()
Definition at line 27 of file common.cpp.
References controller_configuration< columns, rows >::isValid(), controller_configuration< columns, rows >::SPI_CLK, controller_configuration< columns, rows >::SPI_CS, controller_configuration< columns, rows >::SPI_MOSI, and controller_configuration< columns, rows >::useHardwareSpi.
get_multi_conf_SPI()
controller_configuration<4,4>& get_multi_conf_SPI ()
Definition at line 40 of file common.cpp.
References controller_configuration< columns, rows >::isValid(), controller_configuration< columns, rows >::SPI_CS, and controller_configuration< columns, rows >::useHardwareSpi.