LedController: test/common/common.hpp File Reference
common.hpp File Reference
#include "LedController.hpp"
#include <unity.h>
Macros
#define CATCH_FAKEIT catch(const FakeitException& e){std::cout << e.what() << std::endl; const char* msg = e.what().c_str(); TEST_FAIL_MESSAGE(msg);}
#define CATCH_STD catch(const std::exception& e){const char* msg = e.what(); TEST_FAIL_MESSAGE(msg); }
#define SPI_OUTPUT
#define TEST_ASSERT_EQAUL_BYTE_BLOCKS(a, b) for(unsigned int i = 0;i < 8;i++){TEST_ASSERT_EQUAL(a[i],b[i]);};
Functions
controller_configuration< 4, 1 > & get_conf ()
controller_configuration< 4, 1 > & get_conf_SPI ()
controller_configuration< 4, 4 > & get_multi_conf ()
controller_configuration< 4, 4 > & get_multi_conf_SPI ()
template<size_t columns>
ByteRow< columns > in_array ()
Macro Definition Documentation
CATCH_FAKEIT
#define CATCH_FAKEIT catch(const FakeitException& e){std::cout << e.what() << std::endl; const char* msg = e.what().c_str(); TEST_FAIL_MESSAGE(msg);}
Definition at line 13 of file common.hpp.
CATCH_STD
#define CATCH_STD catch(const std::exception& e){const char* msg = e.what(); TEST_FAIL_MESSAGE(msg); }
Definition at line 7 of file common.hpp.
SPI_OUTPUT
#define SPI_OUTPUT
Definition at line 3 of file common.hpp.
TEST_ASSERT_EQAUL_BYTE_BLOCKS
#define TEST_ASSERT_EQAUL_BYTE_BLOCKS (a, b) for(unsigned int i = 0;i < 8;i++){TEST_ASSERT_EQUAL(a[i],b[i]);};
Definition at line 9 of file common.hpp.
Function Documentation
get_conf()
controller_configuration<4,1>& get_conf ()
Definition at line 3 of file common.cpp.
References controller_configuration< columns, rows >::isValid(), controller_configuration< columns, rows >::SPI_CLK, controller_configuration< columns, rows >::SPI_CS, controller_configuration< columns, rows >::SPI_MOSI, and controller_configuration< columns, rows >::useHardwareSpi.
get_conf_SPI()
controller_configuration<4,1>& get_conf_SPI ()
Definition at line 16 of file common.cpp.
References controller_configuration< columns, rows >::isValid(), controller_configuration< columns, rows >::SPI_CS, and controller_configuration< columns, rows >::useHardwareSpi.
get_multi_conf()
controller_configuration<4,4>& get_multi_conf ()
Definition at line 27 of file common.cpp.
References controller_configuration< columns, rows >::isValid(), controller_configuration< columns, rows >::SPI_CLK, controller_configuration< columns, rows >::SPI_CS, controller_configuration< columns, rows >::SPI_MOSI, and controller_configuration< columns, rows >::useHardwareSpi.
get_multi_conf_SPI()
controller_configuration<4,4>& get_multi_conf_SPI ()
Definition at line 40 of file common.cpp.
References controller_configuration< columns, rows >::isValid(), controller_configuration< columns, rows >::SPI_CS, and controller_configuration< columns, rows >::useHardwareSpi.
in_array()
template<size_t columns> ByteRow<columns> in_array ()
Definition at line 22 of file common.hpp.