LedController: LedController Class Reference
LedController Class Reference
This class provied a control interface for MAX7219 and MAX7221 Led display drivers.
#include <LedController.hpp>
Public Member Functions
void activateAllSegments ()
Get all segments out of power-down mode for normal operation.
void activateSegment (unsigned int segmentNumber)
Get the segment out of power-down mode for normal operation.
void clearMatrix ()
clears all segments, turning all LEDs off.
void clearSegment (unsigned int segmentNumber)
clears a given segment, turning all its LEDs off.
void displayOnSegment (unsigned int segmentindex, ByteBlock data)
Display 8 lines on the given segment.
byte getRow (unsigned int segmentNumber, unsigned int row)
get one Row of one segment.
unsigned int getSegmentCount ()
Get the number of configured segments.
void getSegmentData (unsigned int segmentindex, ByteBlock *resultLocation)
Get the Segment Data of a specific Segment.
void init (unsigned int csPin, unsigned int numSegments=4)
initilizes the LedController for use with hardware SPI
void init (unsigned int dataPin, unsigned int clkPin, unsigned int csPin, unsigned int numSegments=4, bool useHardwareSpi=false)
initilizes the LedController
bool isInitilized ()
returns the status of the LedController
LedController ()
Construct a new LedController without initilizing anything.
LedController (unsigned int csPin, unsigned int numSegments=4)
Construct a new LedController for use with hardware SPI.
LedController (unsigned int dataPin, unsigned int clkPin, unsigned int csPin, unsigned int numSegments=4, bool useHardwareSpi=false)
Construct a new LedController object.
LedController (const LedController &other)
The copy constructor for the LedController.
void makeColumns (ByteBlock rowArray, ByteBlock *columnArray)
Turns an array of rows into an array of columns.
void moveDown (byte *shiftedInRow, byte **shiftedOutRow)
moves the data down by one
void moveDown (byte **shiftedOutRow)
moves the data down by one and 0x00 will be shifted in
void moveDown ()
moves the data down by one and 0x00 will be shifted in
byte moveLeft (byte shiftedInColumn=0x00)
moves the data left by one
byte moveRight (byte shiftedInColumn=0x00)
moves the data left by one
void moveUp (byte *shiftedInRow, byte **shiftedOutRow)
moves the data up by one
void moveUp (byte **shiftedOutRow)
moves the data up by oneand 0x00 will be shifted in
void moveUp ()
moves the data up by one and 0x00 will be shifted in
void refreshSegments ()
refreshes all segments displaying the internally stored state of the segments.
void resetMatrix ()
activates all segments, sets to same intensity and cleas them
byte reverse (byte input)
This function changes to bitorder of a byte (useful to mirror "images" you want to display)
void reverse (ByteBlock input, ByteBlock *reversedInput)
Reverse an array of 8 bytes (mirror it)
void rotate180 (ByteBlock input, ByteBlock *rotatedInput)
rotate an byte[8] array by 180 degrees
void setChar (unsigned int segmentNumber, unsigned int digit, char value, boolean dp)
Set the Display a character on a 7-Segment display.
void setColumn (unsigned int segmentNumber, unsigned int col, byte value)
Set one column of a given segment.
void setDigit (unsigned int segmentNumber, unsigned int digit, byte value, boolean dp)
Set a hexadecimal digit on a 7-Segment Display.
void setIntensity (unsigned int newIntesityLevel)
Set the Intensity of the whole matrix to the given value.
void setLed (unsigned int segmentNumber, unsigned int row, unsigned int column, boolean state)
Set a single led to a given value.
void setRow (unsigned int segmentNumber, unsigned int row, byte value)
Set one Row of one segment.
void setScanLimit (unsigned int segmentNumber, unsigned int limit)
Set the number of digits (or rows) to be displayed.
void shutdownAllSegments ()
Set all segments into power-down mode.
void shutdownSegment (unsigned int segmentNumber)
Set the segment in power-down mode.
~LedController ()
Destroy the Led Controller object and free the memory.
Protected Member Functions
void createEmptyRow (byte **row)
this copies an empty row into row
void setIntensity (unsigned int segmentNumber, unsigned int newIntesityLevel)
Set the brightness of the segment.
void spiTransfer (unsigned int segment, byte opcode, byte data)
This function transfers one command to the attached module.
Protected Attributes
byte * emptyRow = nullptr
contains a row full of 0x00
bool initilized = false
True if the LedController is fully initilized.
unsigned int IntensityLevel = 1
The current brightness level of the leds.
ByteBlock * LedStates = nullptr
The state of all the Leds.
unsigned int SegmentCount = 0
The number of connected Segments.
unsigned int SPI_CLK = 0
The pin for the clock signal (CLK)
unsigned int SPI_CS = 0
The pin for the chip select signal (CS)
unsigned int SPI_MOSI = 0
The pin for the data transfer (DIN)
byte * spidata = nullptr
The array for shifting the data to the devices.
bool useHardwareSpi = false
True if hardware spi should be use (a lot faster but you cannot use any pin you want)
Detailed Description
This class provied a control interface for MAX7219 and MAX7221 Led display drivers.
This Controller Class is mainly target at led matracies consisting of more than 1 segment. While it can also handle 7-Segment Displays it is not tested that well.
Warning
This object is not thread safe yet.
Note
If your compiler is STD_CAPABLE the ByteBlock is of the type std::array<byte,8> instead of ByteBlock.
Check if your code has support for the std by calling: static_assert(STD_CAPABLE > 0, "STD not supported")
Todo:
make it threading safe
Definition at line 58 of file LedController.hpp.
Constructor & Destructor Documentation
LedController() [1/4]
LedController::LedController ()
Construct a new LedController without initilizing anything.
Definition at line 26 of file LedController.cpp.
LedController() [2/4]
LedController::LedController (unsigned int csPin, unsigned int numSegments = 4)
Construct a new LedController for use with hardware SPI.
Parameters
csPin The pin to select the led matrix
numSegments the number of connected segments (defualt 4)
Definition at line 28 of file LedController.cpp.
LedController() [3/4]
LedController::LedController (unsigned int dataPin, unsigned int clkPin, unsigned int csPin, unsigned int numSegments = 4, bool useHardwareSpi = false)
Construct a new LedController object.
Parameters
dataPin pin on the Arduino where data gets shifted out (DIN)
clkPin pin for the clock (CLK)
csPin pin for selecting the device (CS)
numSegments The number of segments that will be controlled by the controller (default 4)
useHardwareSpi true if you want to use hardware SPI (view https://www.arduino.cc/en/Reference/SPI for pin config)
Definition at line 30 of file LedController.cpp.
References init().
~LedController()
LedController::~LedController ()
Destroy the Led Controller object and free the memory.
Definition at line 19 of file LedController.cpp.
References emptyRow, initilized, LedStates, and spidata.
LedController() [4/4]
LedController::LedController (const LedController & other)
The copy constructor for the LedController.
Parameters
other the LedController which should have its state copied
Definition at line 40 of file LedController.cpp.
References init(), initilized, LedStates, refreshSegments(), SegmentCount, SPI_CLK, SPI_CS, SPI_MOSI, spidata, and useHardwareSpi.
Member Function Documentation
activateAllSegments()
void LedController::activateAllSegments ()
Get all segments out of power-down mode for normal operation.
Definition at line 235 of file LedController.cpp.
References activateSegment(), initilized, and SegmentCount.
activateSegment()
void LedController::activateSegment (unsigned int segmentNumber)
Get the segment out of power-down mode for normal operation.
Parameters
segmentNumber The segment to control
Definition at line 217 of file LedController.cpp.
References initilized, OP_SHUTDOWN, SegmentCount, and spiTransfer().
clearMatrix()
void LedController::clearMatrix ()
clears all segments, turning all LEDs off.
Definition at line 150 of file LedController.cpp.
References clearSegment(), initilized, and SegmentCount.
clearSegment()
void LedController::clearSegment (unsigned int segmentNumber)
clears a given segment, turning all its LEDs off.
Parameters
segmentNumber The segment to control.
Definition at line 292 of file LedController.cpp.
References initilized, LedStates, SegmentCount, and spiTransfer().
createEmptyRow()
void LedController::createEmptyRow (byte ** row) protected
this copies an empty row into row
Parameters
row the pointer to the byte array that should be used
Definition at line 455 of file LedController.cpp.
References initilized, and SegmentCount.
displayOnSegment()
void LedController::displayOnSegment (unsigned int segmentindex, ByteBlock data)
Display 8 lines on the given segment.
Parameters
segmentindex the Segment number of the desired segment
data an array containing the data for all the pixels that should be displayed on that segment
Definition at line 181 of file LedController.cpp.
References initilized, SegmentCount, and setRow().
getRow()
byte LedController::getRow (unsigned int segmentNumber, unsigned int row)
get one Row of one segment.
Parameters
segmentNumber The Segment which should be modified
row The row which should be modified
Returns
value each bit set to 1 will light up the corresponding Led.
Definition at line 312 of file LedController.cpp.
References initilized, LedStates, and SegmentCount.
getSegmentCount()
unsigned int LedController::getSegmentCount ()
Get the number of configured segments.
Returns
unsigned int The number of configured segments
Definition at line 201 of file LedController.cpp.
References initilized, and SegmentCount.
getSegmentData()
void LedController::getSegmentData (unsigned int segmentindex, ByteBlock * resultLocation)
Get the Segment Data of a specific Segment.
Parameters
segmentindex the index of whose data you want to have
resultLocation the location where the data should be stored
Definition at line 191 of file LedController.cpp.
References initilized, LedStates, and SegmentCount.
init() [1/2]
void LedController::init (unsigned int csPin, unsigned int numSegments = 4)
initilizes the LedController for use with hardware SPI
Parameters
csPin The pin to select the led matrix
numSegments the number of connected segments (defualt 4)
Definition at line 63 of file LedController.cpp.
init() [2/2]
void LedController::init (unsigned int dataPin, unsigned int clkPin, unsigned int csPin, unsigned int numSegments = 4, bool useHardwareSpi = false)
initilizes the LedController
Parameters
dataPin pin on the Arduino where data gets shifted out (DIN)
clkPin pin for the clock (CLK)
csPin pin for selecting the device (CS)
numSegments The number of segments that will be controlled by the controller (default 4)
useHardwareSpi true if you want to use hardware SPI (view https://www.arduino.cc/en/Reference/SPI for pin config)
Definition at line 67 of file LedController.cpp.
References activateSegment(), clearSegment(), emptyRow, initilized, LedStates, OP_DECODEMODE, OP_DISPLAYTEST, SegmentCount, setIntensity(), setScanLimit(), SPI_CLK, SPI_CS, SPI_MOSI, spidata, spiTransfer(), and useHardwareSpi.
isInitilized()
bool LedController::isInitilized ()
returns the status of the LedController
Returns
true the LedController is initilized
false the LedController is not initilized
Definition at line 136 of file LedController.cpp.
References initilized.
makeColumns()
void LedController::makeColumns (ByteBlock rowArray, ByteBlock * columnArray)
Turns an array of rows into an array of columns.
Parameters
rowArray the array of rows of which you want the columns
columnArray The address where the result will be stored
Definition at line 463 of file LedController.cpp.
References initilized.
moveDown() [1/3]
void LedController::moveDown (byte * shiftedInRow, byte ** shiftedOutRow)
moves the data down by one
Parameters
shiftedInRow The row that will be shifted in on the top (default 0x00)
shiftedOutRow The address of the row that will be shifted out on the bottom
Definition at line 475 of file LedController.cpp.
References createEmptyRow(), initilized, LedStates, refreshSegments(), and SegmentCount.
moveDown() [2/3]
void LedController::moveDown (byte ** shiftedOutRow)
moves the data down by one and 0x00 will be shifted in
Parameters
shiftedOutRow The address of the row that will be shifted out on the bottom
Definition at line 540 of file LedController.cpp.
References createEmptyRow(), initilized, moveDown(), and SegmentCount.
moveDown() [3/3]
void LedController::moveDown ()
moves the data down by one and 0x00 will be shifted in
Returns
ByteRow The row the will be shifted out on the bottom
Definition at line 551 of file LedController.cpp.
References createEmptyRow(), initilized, and SegmentCount.
moveLeft()
byte LedController::moveLeft (byte shiftedInColumn = 0x00)
moves the data left by one
Parameters
shiftedInColumn The column that will be shifted in on the right (default 0x00)
Returns
byte The column that gets shifted out on the left
Definition at line 425 of file LedController.cpp.
References initilized, LedStates, refreshSegments(), SegmentCount, and setColumn().
moveRight()
byte LedController::moveRight (byte shiftedInColumn = 0x00)
moves the data left by one
Parameters
shiftedInColumn The column that will be shifted in on the left (default 0x00)
Returns
byte The column that gets shifted out on the right
Definition at line 386 of file LedController.cpp.
References initilized, LedStates, refreshSegments(), SegmentCount, and setColumn().
moveUp() [1/3]
void LedController::moveUp (byte * shiftedInRow, byte ** shiftedOutRow)
moves the data up by one
Parameters
shiftedInRow The row that will be shifted in on the bottom (default 0x00)
shiftedOutRow The address of the row that will be shifted out on the bottom
Definition at line 502 of file LedController.cpp.
References createEmptyRow(), initilized, LedStates, refreshSegments(), and SegmentCount.
moveUp() [2/3]
void LedController::moveUp (byte ** shiftedOutRow)
moves the data up by oneand 0x00 will be shifted in
Parameters
shiftedOutRow The address of the row that will be shifted out on the bottom
Definition at line 529 of file LedController.cpp.
References createEmptyRow(), initilized, moveUp(), and SegmentCount.
moveUp() [3/3]
void LedController::moveUp ()
moves the data up by one and 0x00 will be shifted in
Definition at line 562 of file LedController.cpp.
References createEmptyRow(), initilized, and SegmentCount.
refreshSegments()
void LedController::refreshSegments ()
refreshes all segments displaying the internally stored state of the segments.
Definition at line 374 of file LedController.cpp.
References initilized, LedStates, SegmentCount, and spiTransfer().
resetMatrix()
void LedController::resetMatrix ()
activates all segments, sets to same intensity and cleas them
Definition at line 140 of file LedController.cpp.
References activateAllSegments(), clearMatrix(), initilized, and setIntensity().
reverse() [1/2]
byte LedController::reverse (byte input)
This function changes to bitorder of a byte (useful to mirror "images" you want to display)
Parameters
input The byte that should be reversed
Returns
byte The reversed byte
Definition at line 414 of file LedController.cpp.
reverse() [2/2]
void LedController::reverse (ByteBlock input, ByteBlock * reversedInput)
Reverse an array of 8 bytes (mirror it)
Parameters
input The array that should be mirrored
reversedInput The address where the result will be stored
Definition at line 575 of file LedController.cpp.
References reverse().
rotate180()
void LedController::rotate180 (ByteBlock input, ByteBlock * rotatedInput)
rotate an byte[8] array by 180 degrees
Parameters
input the array that will be rotated
rotatedInput The address where the result will be stored
Definition at line 585 of file LedController.cpp.
References reverse().
setChar()
void LedController::setChar (unsigned int segmentNumber, unsigned int digit, char value, boolean dp)
Set the Display a character on a 7-Segment display.
Note
There are only a few characters that make sense here : '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '0', 'A', 'b', 'c', 'd', 'E', 'F', 'H', 'L', 'P', '.', '-', '_', ' '
Parameters
segmentNumber The number of the desired segment
digit the position of the character on the segment (0..7)
value the character to be displayed.
dp dp if true sets the decimal point
Definition at line 358 of file LedController.cpp.
References initilized, LedStates, SegmentCount, and spiTransfer().
setColumn()
void LedController::setColumn (unsigned int segmentNumber, unsigned int col, byte value)
Set one column of a given segment.
Parameters
segmentNumber The desired Segment number
col The desired column
value The value, this column should have
Definition at line 336 of file LedController.cpp.
References initilized, SegmentCount, and setLed().
setDigit()
void LedController::setDigit (unsigned int segmentNumber, unsigned int digit, byte value, boolean dp)
Set a hexadecimal digit on a 7-Segment Display.
Parameters
segmentNumber The number of the desired Segment
digit the position of the digit on the Segment (0..7)
value the value to be displayed. (0x00..0x0F)
dp if true sets the decimal point
Definition at line 349 of file LedController.cpp.
References initilized, LedStates, SegmentCount, and spiTransfer().
setIntensity() [1/2]
void LedController::setIntensity (unsigned int segmentNumber, unsigned int newIntesityLevel) protected
Set the brightness of the segment.
Parameters
segmentNumber the address of the segment to control
newIntesityLevel the brightness of the display. (0..15)
Definition at line 173 of file LedController.cpp.
References initilized, OP_INTENSITY, SegmentCount, and spiTransfer().
setIntensity() [2/2]
void LedController::setIntensity (unsigned int newIntesityLevel)
Set the Intensity of the whole matrix to the given value.
Note
if you want to save more energy disable segments you don't need or lower the brightness.
Parameters
newIntesityLevel the new brightness of the matrix. (0..15)
Definition at line 160 of file LedController.cpp.
References initilized, IntensityLevel, SegmentCount, and setIntensity().
setLed()
void LedController::setLed (unsigned int segmentNumber, unsigned int row, unsigned int column, boolean state)
Set a single led to a given value.
Parameters
segmentNumber the segment number of the desired led
row the row of the desired led (0..7)
column the column of the desired led (0..7)
state true if it should be on otherwise false
Definition at line 321 of file LedController.cpp.
References initilized, LedStates, SegmentCount, and spiTransfer().
setRow()
void LedController::setRow (unsigned int segmentNumber, unsigned int row, byte value)
Set one Row of one segment.
Parameters
segmentNumber The Segment which should be modified
row The row which should be modified
value each bit set to 1 will light up the corresponding Led.
Definition at line 303 of file LedController.cpp.
References initilized, LedStates, SegmentCount, and spiTransfer().
setScanLimit()
void LedController::setScanLimit (unsigned int segmentNumber, unsigned int limit)
Set the number of digits (or rows) to be displayed.
Note
See datasheet for sideeffects of the scanlimit on the brightness of the display.
Parameters
segmentNumber The segment which should be addressed
limit The number of digits to be displayed (0..7)
Definition at line 287 of file LedController.cpp.
References initilized, OP_SCANLIMIT, SegmentCount, and spiTransfer().
shutdownAllSegments()
void LedController::shutdownAllSegments ()
Set all segments into power-down mode.
Definition at line 225 of file LedController.cpp.
References initilized, SegmentCount, and shutdownSegment().
shutdownSegment()
void LedController::shutdownSegment (unsigned int segmentNumber)
Set the segment in power-down mode.
Parameters
segmentNumber The segment to control
Definition at line 209 of file LedController.cpp.
References initilized, OP_SHUTDOWN, SegmentCount, and spiTransfer().
spiTransfer()
void LedController::spiTransfer (unsigned int segment, byte opcode, byte data) protected
This function transfers one command to the attached module.
Parameters
segment The segment that should execute this command
opcode The command thCLKat should be executed
data The data needed for that command
Definition at line 245 of file LedController.cpp.
References initilized, SegmentCount, SPI_CLK, SPI_CS, SPI_MOSI, spidata, and useHardwareSpi.
Member Data Documentation
emptyRow
byte* LedController::emptyRow = nullptr protected
contains a row full of 0x00
Definition at line 115 of file LedController.hpp.
initilized
bool LedController::initilized = false protected
True if the LedController is fully initilized.
Definition at line 109 of file LedController.hpp.
IntensityLevel
unsigned int LedController::IntensityLevel = 1 protected
The current brightness level of the leds.
Warning
The value needs to be between 0 and 15 (inclusive bounds).
Definition at line 83 of file LedController.hpp.
LedStates
ByteBlock* LedController::LedStates = nullptr protected
The state of all the Leds.
Definition at line 62 of file LedController.hpp.
SegmentCount
unsigned int LedController::SegmentCount = 0 protected
The number of connected Segments.
Definition at line 74 of file LedController.hpp.
SPI_CLK
unsigned int LedController::SPI_CLK = 0 protected
The pin for the clock signal (CLK)
Definition at line 71 of file LedController.hpp.
SPI_CS
unsigned int LedController::SPI_CS = 0 protected
The pin for the chip select signal (CS)
Definition at line 68 of file LedController.hpp.
SPI_MOSI
unsigned int LedController::SPI_MOSI = 0 protected
The pin for the data transfer (DIN)
Definition at line 65 of file LedController.hpp.
spidata
byte* LedController::spidata = nullptr protected
The array for shifting the data to the devices.
Definition at line 95 of file LedController.hpp.
useHardwareSpi
bool LedController::useHardwareSpi = false protected
True if hardware spi should be use (a lot faster but you cannot use any pin you want)
Definition at line 77 of file LedController.hpp.
The documentation for this class was generated from the following files:
src/LedController.hpp
src/LedController.cpp