LedController: test/common/Move.hpp File Reference
Move.hpp File Reference
#include "common.hpp"
Functions
void run_move_multi_tests ()
void run_move_tests ()
template<size_t columns, size_t rows>
void test_down_up (controller_configuration< columns, rows > &conf)
template<size_t columns, size_t rows>
void test_left_right (controller_configuration< columns, rows > &conf)
template<size_t columns, size_t rows>
void test_right_left (controller_configuration< columns, rows > &conf)
template<size_t columns, size_t rows>
void test_up_down (controller_configuration< columns, rows > &conf)
Function Documentation
run_move_multi_tests()
void run_move_multi_tests ()
Definition at line 69 of file Move.cpp.
run_move_tests()
void run_move_tests ()
Definition at line 31 of file Move.cpp.
test_down_up()
template<size_t columns, size_t rows> void test_down_up (controller_configuration< columns, rows > & conf)
Definition at line 83 of file Move.hpp.
References CATCH_FAKEIT, CATCH_STD, LedController< columns, rows >::moveDown(), and LedController< columns, rows >::moveUp().
test_left_right()
template<size_t columns, size_t rows> void test_left_right (controller_configuration< columns, rows > & conf)
Definition at line 21 of file Move.hpp.
References CATCH_FAKEIT, CATCH_STD, LedController< columns, rows >::moveLeft(), and LedController< columns, rows >::moveRight().
test_right_left()
template<size_t columns, size_t rows> void test_right_left (controller_configuration< columns, rows > & conf)
Definition at line 41 of file Move.hpp.
References CATCH_FAKEIT, CATCH_STD, LedController< columns, rows >::moveLeft(), and LedController< columns, rows >::moveRight().
test_up_down()
template<size_t columns, size_t rows> void test_up_down (controller_configuration< columns, rows > & conf)
Definition at line 61 of file Move.hpp.
References CATCH_FAKEIT, CATCH_STD, LedController< columns, rows >::moveDown(), and LedController< columns, rows >::moveUp().